document.write('\
\
\
<h2>Tuoteryhmät</h2>\
                    <table class="table table-striped">\
                        <thead>\
                            <tr>\
                                <th>Tuoteryhmännro</th>\
                                <th>Tuoteryhmä</th>\
                            </tr>\
                        </thead>\
                    <tbody>\
                            <tr>\
                                <td>1</td>\
                                <td>Toimistotarvikkeet</td>\
                            </tr>\
                            <tr>\
                                <td>2</td>\
                                <td>Pasta</td>\
                            </tr>\
                            <tr>\
                                <td>3</td>\
                                <td>Huonekalut</td>\
                            </tr>\
                        </tbody>\
                    </table>\
\
');